### ISSUE TITLE
Tool icons on the top-right

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#266]
**Description of new feature**

- [x] Two icons should always be visible: shift/box select and download.  The rest can just go in the hamburger menu all the time.
- [ ] New list of icons / tools in the hamburger:
  - [x] Undo
  - [x] Delete -- removed (also see #262)
  - [x] Restore
  - [x] Zoom in
  - [x] Zoom out
  - [x] Fit
  - [x] Shift-Select (see #265)
  - [x] Download -- moved outside
  - [ ] Share by email: Open email dialog (related to #261)
- [x] Download icon should be a line with an arrow
- [x] Same icon for download gene list
- [x] It needs to be clear in the tooltip for the main download what you get: Download
- [x] The one download option downloads everything -- the enrichment files and the images in one ZIP

**Motivation for new feature**

- There are a lot of icons, and it's difficult to find the important ones, like download.

**Comment by chrtannus** [comment]
This is how the toolbar looks now when _shift-select_ and _download_ are visible but the other ones are in the **overflow menu**:

<img width="630" alt="overflow-menu" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/0a356154-60dd-4462-ac06-57b78f0385fc">

(*) Notice that I'm suggesting we use the more standard vertical ellipsis icon in this scenario, instead of the hamburger one, which is more associated with a mobile device's menu and usually contains all the other menu/toolbar options. I just find that the hamburger icon would not stand out as much here.

----
This is how it look on small screens (**mobile**):

<img width="374" alt="mobile-menu" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/2f6e2ddf-c146-4d19-aba9-69f0448816a4">

(*) I suggest we hide all the toolbar icons in this scenario--the screen is just too small--and that we use the hamburger icon.

**Comment by chrtannus** [comment]
The mobile/overflow menu now renders toggleable items properly:

<img width="374" alt="toggleable-menu-item" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/6b60dc5e-d1a4-452a-8ffc-4f3b2741812d">

**Comment by chrtannus** [comment]
<img width="830" alt="toolbar" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/506551b7-d9cd-409b-b442-7c5452bed52a">
